config/routes.rb
Rails.application.routes.draw do
  resources :alumnos
 #get 'static/about'
get 'about', controller: :static, action: :about, alias: 'about'
  
 #get 'static/services'
get 'services', controller: :static, action: :services, alias: 'services'

#get 'static/faq'
get 'faq', controller: :static, action: :faq, alias: 'faq'

get 'contact', controller: :static, action: :contact, alias:'contact'
  #get 'home/index'

post 'static/mimetodo'
root 'home#index'
get 'static/mypage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alumno.rb
class Alumno < ApplicationRecord
	validates :nombres, presence:{message: "es obligatorio"}
	validates :dni, length: {
		minimum: 8,
		too_short: "debe tener 8 digitos."
	}, uniqueness: {
		message: "ya esta registrado, ingrese otro."
	}

	validates :email, confirmation: {
		case_sensitive: false
	}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alumno_params
      params.require(:alumno).permit(:nombres, :dni, :email, :email_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
 layout 'static'
  def about
  end

  def services
  end

  def mypage
  	render :services
  end

  def faq
  end

  def contact
  end

  def mimetodo
    puts "Datos recibidos del formulario."

    a = params[:upc][:titulo]
    b = params[:upc][:descripcion]

    puts "Valor del titulo enviado: #{a}"
    puts "Valor de la descripcion enviada: #{b}"
  end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/alumnos/_form.html.erb
<%= form_with(model: alumno, local: true) do |form| %>
  <% if alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
        <% alumno.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :dni %>
    <%= form.text_field :dni,:class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email_confirmation %>
    <%= form.text_field :email_confirmation, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "guardar datos", :class => "btn btn-outline-success" %>
  </div>
<% end %>

app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumnos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Dni</th>
      <th>Email</th>
      <th>Email confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.nombres %></td>
        <td><%= alumno.dni %></td>
        <td><%= alumno.email %></td>
        <td><%= alumno.email_confirmation %></td>
        <td><%= link_to 'Show', alumno %></td>
        <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
        <td><%= link_to 'Destroy', alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumno', new_alumno_path %>

app/views/alumnos/new.html.erb
<h1>Nuevo Alumno</h1>

<%= render 'form', alumno: @alumno %>

<%= link_to 'Back', alumnos_path %>

app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @alumno.nombres %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @alumno.dni %>
</p>

<p>
  <strong>Email:</strong>
  <%= @alumno.email %>
</p>

<p>
  <strong>Email confirmation:</strong>
  <%= @alumno.email_confirmation %>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
	<div class="col-8">

				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
		    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
		  </ol>
		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" role="listbox">
		    <div class="item active">
		      <%= image_tag "img1.jpg", html: { alt: "img1" } %>
		      <div class="carousel-caption">
		        <h3>Our restaurants</h3>
		        <p>The best for you</p>
		      </div>
		    </div>
		    <div class="item">
		      <%= image_tag "img2.png", html: { alt: "img2" } %>
		      <div class="carousel-caption">
		        <h3>Our service</h3>
		        <p>Best quality</p>
		      </div>
		    </div>
		    <div class="item">
		      <%= image_tag "http://www.agrocostasac.com/web/wp-content/uploads/2019/04/logoacosta.jpg", html: { alt: "rest_slider3" }%>
		      <div class="carousel-caption">
		        <h3>Our service</h3>
		        <p>Best quality</p>
		      </div>
		    </div>

		    <div class="item">
		      <%= image_tag "img3.png", html: { alt: "img3" }%>
		      <div class="carousel-caption">
		        <h3>Our service</h3>
		        <p>Best quality</p>
		      </div>
		    </div>
		  </div>
		  <!-- Controls -->
		  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>
		</div>
	<div class="col-4">
		<form>
			<div class="form-group">
				<label for="exampleInputEmail1">Email address</label>
				<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
				<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
			</div>
			<div class="form-group">
				<label for="exampleInputPassword1">Password</label>
				<input type="password" class="form-control" id="exampleInputPassword1">
			</div>
			<div class="form-group form-check">
				<input type="checkbox" class="form-check-input" id="exampleCheck1">
				<label class="form-check-label" for="exampleCheck1">Check me out</label>
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
  </div>
</div>
		<div class="jumbotron">
		  <h1>Welcome</h1>
		  <p>It is a pleasure to have you at our site</p>
		  <p><a class="btn btn-primary btn-lg" href=<%= root_path %> role="button">Learn more</a></p>
		</div>
	</div>

	

app/views/layouts/_menu.html.erb
<!--
<ul>
	<li style = "display: inline"><%= link_to "Home",root_path %></li>
	<li style = "display: inline"><%= link_to "About Us",about_path %></li>
	<li style = "display: inline"><%= link_to "Our Services",services_path %></li>
	<li style = "display: inline"><%= link_to "faq",faq_path %></li>
<ul>
-->

<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href=".">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/about">Abou Us</a>
  </li>
  <li class="nav-item">
    <%= link_to 'Services', services_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Faq', faq_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'contact_Us', contact_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Listar Alunmos', alumnos_path, :class => "nav-link" %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: "layouts/menu" %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: "layouts/menu" %>
    
    <div class="container">
      <%= yield :intro %>
      <%= yield %>
    </div>

    <script type="text/javascript">
      (function(){
      'use strict';
        window.addEventListener('load', function() {
          var forms = document.getElementsByClassName('needs-validation')
          var validation = Array.prototype.filter.call(forms, function(form) {
            form.addEventListener('submit', function(event) {
              if (form.checkValidity() == false) {
                event.preventDefault();
                event.stopPropagation();
              }
              form.classList.add('was-validated');
            }, false);
          });
        }, false);
      })();
    </script>
  </body>
</html>